### PR TITLE
Added Spanish Language.

### PR DESCRIPTION
**Pull request by xSamiVS**
- Created `es.json` with Spanish Language.

### CODE REVIEW

**Comment by MonkeyWhisper** [comment]
> * Created `es.json` with Spanish Language.

Add it to the README as well

**Comment by xSamiVS** [comment]
Added Languages Section to README.md #62

**Comment by MonkeyWhisper** [comment]
> Added Languages Section to README.md #62

Edit this pending PR

**Comment by xSamiVS** [comment]
> > Added Languages Section to README.md #62
> 
> Edit this pending PR

Ready, idk why sent as other PR.

**Pull request merged**
