### PR TITLE
🔑 Added Key bindings, Noclip and Admin

### PR DESCRIPTION
**Pull request by Doxria**

### CODE REVIEW

**Comment by lenzh** [comment]
IMO just a feature for personal use

**Comment by Doxria** [comment]
Yes, you are right, but "ps-adminmenu" provides ease of access for people who use it and it is a changeable combination.

**Comment by Doxria** [comment]
In addition, the option to turn key assignments on and off as an option via the Config.lua file has been added.

**Review by i-kulgu — APPROVED** [review]
I like the addition for keybindings as a config option, it's easier to use for some quick actions.
People can choose whether to use it or not.
I have tested it out without any issues, so IMO it will be a nice feature.

**Comment by lenzh** [comment]
can u make use of the OX key bind registery

**Comment by lenzh** [comment]
and registercommand aswell

**Comment by RazerGhost** [comment]
this could also work right?

`if Config.Keybindings then
    lib.addKeybind({
        name = 'Admin',
        description = 'Toggle the Admin menu',
        defaultKey = Config.AdminKey,
        onPressed = function()
            ExecuteCommand('admin')
        end
    })

    lib.addKeybind({
        name = 'Admin',
        description = 'Toggle the Admin menu',
        defaultKey = Config.NoclipKey,
        onPressed = function()
            TriggerEvent('ps-adminmenu:client:ToggleNoClip')
        end
    })
end`

**Comment by Doxria** [comment]
> can u make use of the OX key bind registery
> 
> https://overextended.dev/ox_lib/Modules/AddKeybind/Client

Tnks for your comment, I did the update as you said

**Comment by Doxria** [comment]
> this could also work right?
> 
> ```
>   if Config.Keybindings then
>       lib.addKeybind({
>           name = 'Admin',
>           description = 'Toggle the Admin menu',
>           defaultKey = Config.AdminKey,
>           onPressed = function()
>               ExecuteCommand('admin')
>           end
>       })
>   
>       lib.addKeybind({
>           name = 'Admin',
>           description = 'Toggle the Admin menu',
>           defaultKey = Config.NoclipKey,
>           onPressed = function()
>               TriggerEvent('ps-adminmenu:client:ToggleNoClip')
>           end
>       })
>   end
> ```

Thanks for your comment, it was already similar to yours but I updated it like this:
```lua
-- Key Bindings
local toogleAdmin = lib.addKeybind({ name = 'toogleAdmin', description = locale("command_admin_desc"), defaultKey = Config.AdminKey,
    onPressed = function(self)
	ExecuteCommand('admin')
    end
end})

local toogleNoclip = lib.addKeybind({ name = 'toogleNoclip', description = locale("command_noclip_desc"), defaultKey = Config.NoclipKey,
    onPressed = function(self)
	TriggerEvent(Config.Actions["noclip"].event, Config.Actions["noclip"])
    end
end})
if Config.Keybindings then
	toogleAdmin:disable(false)
	toogleNoclip:disable(false)
else
	toogleAdmin:disable(true)
	toogleNoclip:disable(true)
end
```

**Pull request closed without merging**
