### PR TITLE
Just a QOL addition for throwing away unused items AKA Trash.

### PR DESCRIPTION
**Pull request by RazerGhost**
It should correctly delete/clear the trash depending on the inventory. The qb-inventory event should also be correct, but I have not tested it.

### CODE REVIEW

**Comment by lenzh** [comment]
does the trash delete instant or after restart?

**Comment by RazerGhost** [comment]
> does the trash delete instant or after restart?
It does on the ox version and should on the qb/ps version as its a copy from how qb-policejob does it.

**Comment by RazerGhost** [comment]
Could be a slight problem but sometimes the trash for ox inventory only works after a script restart. Still looking for a fix to this.

**Comment by MonkeyWhisper** [comment]
What's the status on this PR? Has it been teted?

**Comment by RazerGhost** [comment]
> What's the status on this PR? Has it been tested?
> 
> Closed by accident

Aah that's alright, so it does work but having the config auto check the inventory doesn't quite seem to work so I have to manually set the inventory for ox_inventory

**Comment by RazerGhost** [comment]
As for the QB inventory and others, I have not tested them but they should be correct

**Comment by RazerGhost** [comment]
Temporarily closing this until I am able to fix ox integration :)

**Pull request closed without merging**
